export const FETCH_ALL_JOBS_REQUEST = 'Home/FETCH_ALL_JOBS_REQUEST';
export const FETCH_ALL_JOBS_SUCCESS = 'Home/FETCH_ALL_JOBS_SUCCESS';
export const FETCH_ALL_JOBS_FAILURE = 'Home/FETCH_ALL_JOBS_FAILURE';
