export const APPLY_FOR_JOB_REQUEST = 'APPLY_FOR_JOB_REQUEST';
export const APPLY_FOR_JOB_SUCCESS = 'APPLY_FOR_JOB_SUCCESS';
export const APPLY_FOR_JOB_FAILURE = 'APPLY_FOR_JOB_FAILURE';

export const CHECK_APPLICATION_REQUEST = 'CHECK_APPLICATION_REQUEST';
export const CHECK_APPLICATION_SUCCESS = 'CHECK_APPLICATION_SUCCESS';
export const CHECK_APPLICATION_FAILURE = 'CHECK_APPLICATION_FAILURE';