export const FETCH_JOB_DETAIL_REQUEST = 'JobDetail/FETCH_JOB_DETAIL_REQUEST';
export const FETCH_JOB_DETAIL_SUCCESS = 'JobDetail/FETCH_JOB_DETAIL_SUCCESS';
export const FETCH_JOB_DETAIL_FAILURE = 'JobDetail/FETCH_JOB_DETAIL_FAILURE';
